FROM node:22-bookworm

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

RUN npx playwright install --with-deps chromium

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

CMD ["/bin/sh", "-c", "npx playwright test;echo 'Tests running finished'; tail -f /dev/null"]