# Build app
FROM node:22-bookworm AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build -- --configuration=testcontainer

# Serve app ising http-server
FROM node:22-bookworm AS server

WORKDIR /app

RUN npm install -g http-server

COPY --from=build /app/dist/GateEntryExit ./dist

EXPOSE 4200

# dist or dist/browser based on angular version
# CMD ["http-server", "dist/browser", "-p", "4200", "-a", "0.0.0.0"]
CMD ["http-server", "dist", "-p", "4200", "-a", "0.0.0.0"]


